# Site settings
title: 音の立ち上がり検出に関するブログの翻訳
email: tidnlyam@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  自分の学習のために、http://www.badlogicgames.com/wordpress/?cat=18 を翻訳したものです。
  だいぶ超訳です。特に許可とかとってないのでフェアユースでお願いします。
  誤りを見つけたら pull request いただけると助かります。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: tily
github_username:  tily

# Build settings
markdown: kramdown
